baseURL = '/'
languageCode = 'en-us'
title = 'U2 Aerial Photography of Egypt'
theme = 'starter'

disableKinds = ['taxonomy', 'term']

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
		footnote = true
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Brown Digital Repository'
    url = 'https://repository.library.brown.edu/studio/collections/bdr:88np2gke/'
    weight = 100